sudo: required
services:
 - docker
 
before_install:
 - docker build -t migab/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run -e CI=true migab/react-test npm test

after_success:
 - docker build -t migab/multi-client ./client
 - docker build -t migab/multi-nginx ./nginx
 - docker build -t migab/multi-serwer ./server
 - docker build -t migab/multi-worker ./worker
 
 #Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Take those images and push them to the docker hub
 - docker push migab/multi-client
 - docker push migab/multi-nginx
 - docker push migab/multi-serwer
 - docker push migab/multi-worker
language: generic 